### ISSUE TITLE
Retrieval of player owner unexpectedly fails

### ISSUE THREAD

**Issue by DSH105** [DSH105/EchoPet#410]
Recently reported issue (by PhanaticD) regarding entity ticking (pet owner suddenly disappears judging by a quick look). Not sure exactly what the cause of this might be as of yet.

```
[18:40:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.getPlayerOwner(EntityPet.java:130) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.onLive(EntityPet.java:298) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.onLive(EntityPacketPet.java:71) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:461) ~[?:?]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        ... 4 more
[18:40:18] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.getPlayerOwner(EntityPet.java:130) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.onLive(EntityPet.java:298) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.onLive(EntityPacketPet.java:71) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:461) ~[?:?]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [factions.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
```

**Comment by DSH105** [comment]
#462 might have been related to this; is the problem still occurring?

**Comment by DSH105** [comment]
After a quick investigation, I think it's safe to conclude that #462 has indeed resolved this issue (unless of course anyone else is still experiencing it).
