### ISSUE TITLE
Unable to determine proper configuration of usage for 1.7.10 with API

### ISSUE THREAD

**Issue by Cryptite** [DSH105/EchoPet#466]
I'm unsure what the proper configuration of dependencies are. I'm running a spigot server running 1.7.10. I've just upgraded from WorldGuard 5.x to 6.0 which begot updating EchoPet to 3.5. However, I'm now unsure what dependency to use with Maven (API, not API?).

I can try to describe a bit more, but I've tried a variety of combinations, some yielding a NullException when trying to getEchoPetAPI(), some yielding ClassNoFound errors with 1.8 spigot protocol stuff (but still on 1.7.10); others blowing up with WG region checks. 

Currently getting a NullPointerException on 2.2.5-SNAPSHOT when trying to check hasPet()
java.lang.NullPointerException
	at io.github.dsh105.echopet.api.EchoPetAPI.hasPet(EchoPetAPI.java:108) ~[?:?]

Any ideas?

**Comment by Cryptite** [comment]
Which version do I want to grab from CI to support 1.7.10 as well as WG6?

**Comment by Cryptite** [comment]
Currently I'm running EchoPet v2.5.0 from the bukkitdev page and beset with the following error when I try to spawn a pet:

Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_7_R4.DataWatcher.watch(DataWatcher.java:105) ~[spigot.jar:git-Spigot-1627]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.initiateEntityPet(EntityPet.java:90) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.<init>(EntityPet.java:69) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityBatPet.<init>(EntityBatPet.java:35) ~[?:?]
	at sun.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.BatPet.<init>(BatPet.java:36) ~[?:?]
	at sun.reflect.GeneratedConstructorAccessor75.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	... 12 more

**Comment by DSH105** [comment]
I'm assuming that stracktrace was a conflict specific to a 1.7/1.8 protocol Spigot build. Is this issue still occurring?

(My apologies for the delayed reply).

**Comment by Cryptite** [comment]
Must've been. I seem to have it working now (as of around 1.8.3).
