### ISSUE TITLE
Mob's have no gui..

### ISSUE THREAD

**Issue by lukemango2** [DSH105/EchoPet#469]
I did /pet wolf, it just spawned a wolf that did nothing. It wouldn't follow you it wouldn't work when you rightclick it to change it. It just didn't work. I'm running 1.7.10 - 1.8 spigot.

Log:

```
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
31.12 11:21:07 [Server] INFO Caused by: java.lang.IllegalStateException: Failed to create pet object for oblivionff
31.12 11:21:07 [Server] INFO ... 12 more
31.12 11:21:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot1710w18.jar:git-Spigot-1649]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
31.12 11:21:07 [Server] INFO at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
31.12 11:21:07 [Server] INFO Caused by: com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for oblivionff
```

**Comment by TheChampTF** [comment]
Environment:
Java version: 1.8.0_31 Oracle Corporation
Operating system: Linux 2.6.38-8-server amd64
Bukkit version: git-Bukkit-bbf72f3 (MC: 1.8)

Plugin: EchoPet v2.6.0-b28

Same issue:

[18:33:17 WARN]: [EchoPet] Task #148 for EchoPet v2.6.0-b28 generated an exception
com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for MrJacen
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPetFromFile(PetManager.java:237) ~[?:?]
	at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:73) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$1.run(PetOwnerListener.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:653) [craftbukkit.jar:git-Bukkit-bbf72f3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit.jar:git-Bukkit-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit.jar:git-Bukkit-bbf72f3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.IllegalStateException: Failed to create pet object for MrJacen
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.removePet(Pet.java:208) ~[?:?]
	at com.dsh105.echopet.api.PetManager.removePet(PetManager.java:327) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R1.SpawnUtil.spawn(SpawnUtil.java:55) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R1.SpawnUtil.spawn(SpawnUtil.java:33) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.SquidPet.<init>(SquidPet.java:30) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
