### ISSUE TITLE
Echopets 2.5.0 generating an error

### ISSUE THREAD

**Issue by dierke9** [DSH105/EchoPet#482]
When i install Echopets version 2.5.0 And try to spawn in a pet it says that an internal error occured when looking in the console i can see an error. How can i fix this problem ?
Greetings Dierke9
Error:

```
[16:55:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet wolf' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[Spigot1.7.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot1.7.jar:git-Spigot-1571]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:65) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:65) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WolfPet.<init>(WolfPet.java:40) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WolfPet.<init>(WolfPet.java:40) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/spigotmc/ProtocolData$IntByte
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityAgeablePet.initDatawatcher(EntityAgeablePet.java:56) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityWolfPet.initDatawatcher(EntityWolfPet.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.c(EntityPet.java:468) ~[?:?]
	at net.minecraft.server.v1_7_R4.Entity.<init>(Entity.java:161) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityLiving.<init>(EntityLiving.java:96) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityInsentient.<init>(EntityInsentient.java:38) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityCreature.<init>(EntityCreature.java:25) ~[Spigot1.7.jar:git-Spigot-1571]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.<init>(EntityPet.java:67) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityAgeablePet.<init>(EntityAgeablePet.java:34) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityWolfPet.<init>(EntityWolfPet.java:42) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WolfPet.<init>(WolfPet.java:40) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.spigotmc.ProtocolData$IntByte
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[Spigot1.7.jar:git-Spigot-1571]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:83) ~[Spigot1.7.jar:git-Spigot-1571]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityAgeablePet.initDatawatcher(EntityAgeablePet.java:56) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityWolfPet.initDatawatcher(EntityWolfPet.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.c(EntityPet.java:468) ~[?:?]
	at net.minecraft.server.v1_7_R4.Entity.<init>(Entity.java:161) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityLiving.<init>(EntityLiving.java:96) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityInsentient.<init>(EntityInsentient.java:38) ~[Spigot1.7.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.EntityCreature.<init>(EntityCreature.java:25) ~[Spigot1.7.jar:git-Spigot-1571]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.<init>(EntityPet.java:67) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityAgeablePet.<init>(EntityAgeablePet.java:34) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityWolfPet.<init>(EntityWolfPet.java:42) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WolfPet.<init>(WolfPet.java:40) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_71]
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot1.7.jar:git-Spigot-1571]
	... 12 more
```

**Comment by DSH105** [comment]
Please update the plugin.

**Comment by dierke9** [comment]
Well the next update i can find is the one for 1.7.1 but my server is 1.7.9

**Comment by DSH105** [comment]
Most EchoPet releases retain compatibility for multiple server versions. The latest release, v2.6.0, is compatoble with anything from 1.7.2 through to 1.8.
