### ISSUE TITLE
Game and server crash

### ISSUE THREAD

**Issue by pipfan101** [DSH105/EchoPet#486]
I host my own servers for my friends and I. The only time my server crashes is as soon as I press enter for getting a pet through this plugin. It crashes both my game and server. Any help?

**Comment by pipfan101** [comment]
Crash report: Help anyone?
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/9/15 8:51 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
	at net.minecraft.server.v1_7_R4.DataWatcher.getInt(SourceFile:91)
	at com.dsh105.echopet.compat.nms.v1_7_R4.entity.EntityAgeablePet.isBaby(EntityAgeablePet.java:84)
	at net.minecraft.server.v1_7_R4.EntityLiving.bg(EntityLiving.java:1168)
	at net.minecraft.server.v1_7_R4.EntityInsentient.r(EntityInsentient.java:106)
	at net.minecraft.server.v1_7_R4.EntityInsentient.C(EntityInsentient.java:115)
	at net.minecraft.server.v1_7_R4.Entity.h(Entity.java:241)
	at net.minecraft.server.v1_7_R4.EntityLiving.h(EntityLiving.java:1360)
	at net.minecraft.server.v1_7_R4.EntityInsentient.h(EntityInsentient.java:150)
	at com.dsh105.echopet.compat.nms.v1_7_R4.entity.EntityPet.h(EntityPet.java:448)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1418)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1396)
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1281)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:481)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:649)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.server.v1_7_R4.DataWatcher.getInt(SourceFile:91)
	at com.dsh105.echopet.compat.nms.v1_7_R4.entity.EntityAgeablePet.isBaby(EntityAgeablePet.java:84)
	at net.minecraft.server.v1_7_R4.EntityLiving.bg(EntityLiving.java:1168)
	at net.minecraft.server.v1_7_R4.EntityInsentient.r(EntityInsentient.java:106)
	at net.minecraft.server.v1_7_R4.EntityInsentient.C(EntityInsentient.java:115)
	at net.minecraft.server.v1_7_R4.Entity.h(Entity.java:241)
	at net.minecraft.server.v1_7_R4.EntityLiving.h(EntityLiving.java:1360)
	at net.minecraft.server.v1_7_R4.EntityInsentient.h(EntityInsentient.java:150)
	at com.dsh105.echopet.compat.nms.v1_7_R4.entity.EntityPet.h(EntityPet.java:448)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1418)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1396)

-- Entity being ticked --
Details:
	Entity Type: Sheep-Pet (com.dsh105.echopet.compat.nms.v1_7_R4.entity.type.EntitySheepPet)
	Entity ID: 988
	Entity Name: entity.Sheep-Pet.name
	Entity's Exact location: 62.70, 227.00, 131.13
	Entity's Block location: World: (62,227,131), Chunk: (at 14,14,3 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1281)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:481)

-- Affected level --
Details:
	Level name: Hunger Games
	All players: 1 total; [EntityPlayer['SonicHorizon'/484, l='Hunger Games', x=62.70, y=227.00, z=131.13](SonicHorizon at 62.704342813598785,227.0,131.13186196223558)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -374067646865625739
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (55,227,129), Chunk: (at 7,14,1 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5759649 game time, 5094000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 115567 (now: false), thunder time: 10221 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:649)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 553546648 bytes (527 MB) / 1011351552 bytes (964 MB) up to 1011351552 bytes (964 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	CraftBukkit Information: 
   Running: CraftBukkit version git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) true
   Plugins: { ChairStairs v1.1 com.axeldios.ChairStairs.ChairStairs [AxelDios], Pixelator v1.2.1 com.darkblade12.pixelator.Pixelator [DarkBlade12], MultiWorld v5.0.0 multiworld.MultiWorldPlugin [ferrybig], WorldEdit v5.5.8 com.sk89q.worldedit.bukkit.WorldEditPlugin [], Vault v1.5.2-b33 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], WorldGuard v5.9 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], Essentials v2.13.1 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], ChessCraft v2.5.2-SNAPSHOT me.desht.chesscraft.ChessCraft [desht, jascotty2], EssentialsProtect v2.13.1 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsSpawn v2.13.1 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], ChestCommands v3.0.8 com.gmail.filoghost.chestcommands.ChestCommands [], HungerGames v3.1 me.minebuilders.hg.HG [bob7l], Timeismoney v1.5 me.Phil.Timeismoney.Timeismoney [], EssentialsChat v2.13.1 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], EchoPet v2.6.0-b28 com.dsh105.echopet.EchoPetPlugin [DSH105], EssentialsAntiBuild v2.13.1 com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally],}
   Warnings: DEFAULT
   Threads: { WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), sun.java2d.Disposer.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #2: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], RUNNABLE Attach Listener: [], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-13: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), me.desht.chesscraft.results.Results.pollDatabaseUpdate(Results.java:260), me.desht.chesscraft.results.DatabaseUpdaterTask.run(DatabaseUpdaterTask.java:21), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.CrashReport.a(CrashReport.java:230), net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1283), net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:481), net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:649), net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258), net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], WAITING pool-4-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-3-thread-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], RUNNABLE Signal Dispatcher: [], RUNNABLE Netty IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32._getch(Native Method), org.fusesource.jansi.internal.WindowsSupport.readByte(WindowsSupport.java:46), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readByte(WindowsTerminal.java:184), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:53), org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:151), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:32)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from 9891-9921{WorldEdit:com.sk89q.worldedit.bukkit.SessionTimer@9869,}
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 5; [EntityPlayer['SonicHorizon'/484, l='Hunger Games', x=62.70, y=227.00, z=131.13](SonicHorizon at 62.704342813598785,227.0,131.13186196223558)]
	Is Modded: Definitely; Server brand changed to 'CraftBukkit'
	Type: Dedicated Server (map_server.txt)
