### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by oloflarsson** [DSH105/EchoPet#493]
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/20/15 9:04 AM
Description: Ticking entity

java.lang.IllegalArgumentException: pitch must be finite
	at org.bukkit.Location.checkFiniteFloat(Location.java:613)
	at org.bukkit.Location.setPitch(Location.java:226)
	at org.bukkit.Location.<init>(Location.java:49)
	at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.getLocation(CraftEntity.java:184)
	at com.dsh105.echopet.libs.dsh105.GeometryUtil.getNearbyEntities(GeometryUtil.java:117)
	at com.dsh105.echopet.libs.dsh105.GeometryUtil.getNearbyPlayers(GeometryUtil.java:145)
	at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:94)
	at com.dsh105.echopet.api.pet.Pet.removePet(Pet.java:209)
	at com.dsh105.echopet.api.PetManager.removePet(PetManager.java:327)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.onLive(EntityPet.java:290)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.s_(EntityPet.java:444)
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
	at java.lang.Thread.run(Thread.java:745)
```

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/20/15 5:35 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82)
	at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.getLocation(EntityPet.java:130)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.ai.PetGoalFollowOwner.tick(PetGoalFollowOwner.java:124)
	at com.dsh105.echopet.compat.api.ai.PetGoalSelector.updateGoals(PetGoalSelector.java:175)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.doTick(EntityPet.java:224)
	at net.minecraft.server.v1_8_R1.EntityLiving.m(EntityLiving.java:1616)
	at net.minecraft.server.v1_8_R1.EntityInsentient.m(EntityInsentient.java:332)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityAgeablePet.m(EntityAgeablePet.java:60)
	at net.minecraft.server.v1_8_R1.EntityLiving.s_(EntityLiving.java:1477)
	at net.minecraft.server.v1_8_R1.EntityInsentient.s_(EntityInsentient.java:193)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.s_(EntityPet.java:442)
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
	at java.lang.Thread.run(Thread.java:745)
```

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/20/15 2:58 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82)
	at com.dsh105.echopet.api.pet.Pet.removePet(Pet.java:208)
	at com.dsh105.echopet.api.PetManager.removePet(PetManager.java:327)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.onLive(EntityPet.java:290)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.type.EntityWolfPet.onLive(EntityWolfPet.java:96)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.s_(EntityPet.java:444)
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
	at java.lang.Thread.run(Thread.java:745)
```

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2/20/15 9:15 AM
Description: Ticking entity

java.lang.IllegalArgumentException: x must be finite
	at org.bukkit.Location.checkFinite(Location.java:607)
	at org.bukkit.Location.setX(Location.java:95)
	at org.bukkit.Location.<init>(Location.java:46)
	at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.getLocation(CraftEntity.java:184)
	at com.dsh105.echopet.libs.dsh105.GeometryUtil.getNearbyEntities(GeometryUtil.java:117)
	at com.dsh105.echopet.libs.dsh105.GeometryUtil.getNearbyPlayers(GeometryUtil.java:145)
	at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:94)
	at com.dsh105.echopet.api.pet.Pet.removePet(Pet.java:209)
	at com.dsh105.echopet.api.PetManager.removePet(PetManager.java:327)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.onLive(EntityPet.java:290)
	at com.dsh105.echopet.compat.nms.v1_8_R1.entity.EntityPet.s_(EntityPet.java:444)
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by DSH105** [comment]
In regards to: `java.lang.IllegalArgumentException: pitch must be finite` and `java.lang.IllegalArgumentException: x must be finite`, I believe I answered that in your other bug report. As for the others, that issue has been reported in #494.
