### ISSUE TITLE
Internal Server Error on using /pet cow(or any other pet)

### ISSUE THREAD

**Issue by viddie** [DSH105/EchoPet#506]
I am getting an Error while trying to perform /pet cow, or any other pet.
Console says:

```
[17:50:45 INFO]: viddie issued server command: /pet human
>
[17:50:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet human' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[spigot.jar:git-Spigot-1571]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1571]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:65) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
        at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
        at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
        at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
        at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
        at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
        at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:65) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
        at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
        at com.dsh105.echopet.api.pet.PacketPet.<init>(PacketPet.java:30) ~[?:?]
        at com.dsh105.echopet.api.pet.type.HumanPet.<init>(HumanPet.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
        at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
        at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
        at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
        at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
        at com.dsh105.echopet.api.pet.PacketPet.<init>(PacketPet.java:30) ~[?:?]
        at com.dsh105.echopet.api.pet.type.HumanPet.<init>(HumanPet.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
        at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
        at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
        at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
        ... 12 more
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_7_R4.DataWatcher.watch(DataWatcher.java:105) ~[spigot.jar:git-Spigot-1571]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.initiateEntityPet(EntityPet.java:90) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.<init>(EntityPet.java:69) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.<init>(EntityPacketPet.java:50) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityHumanPet.<init>(EntityHumanPet.java:36) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:136) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:49) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:35) ~[?:?]
        at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
        at com.dsh105.echopet.api.pet.PacketPet.<init>(PacketPet.java:30) ~[?:?]
        at com.dsh105.echopet.api.pet.type.HumanPet.<init>(HumanPet.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:141) ~[?:?]
        at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:124) ~[?:?]
        at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:406) ~[?:?]
        at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:45) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
        ... 12 more
```

I have EchoPet version 2.5.0 for Spigot 1.7.10, hope that ist the correct version.
I hope you can help me out, -viddie

**Comment by DSH105** [comment]
The protocol 1.7/1.8 Spigot never worked that well with EchoPet (due to its ancient internals). Try updating to 1.8 with EchoPet v2.6.0.
