### ISSUE TITLE
Echopet Will Not Load On Spigot 1.8

### ISSUE THREAD

**Issue by TheCellMC** [DSH105/EchoPet#520]
As soon as I try to start my server, I receive an error which is due to the plugin echopet.

This is the error log:

```
[14:31:34 INFO]: [EchoPet] Loading EchoPet v2.6.0-b28
[14:31:34 INFO]: [EchoPet] Enabling EchoPet v2.6.0-b28
[14:31:34 ERROR]: Error occurred while enabling EchoPet v2.6.0-b28 (Is it up to date?)
java.lang.UnsupportedClassVersionError: com/dsh105/echopet/libs/dsh105/logging/Log : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at com.dsh105.echopet.compat.api.plugin.EchoPet.<clinit>(EchoPet.java:28) ~[?:?]
	at com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:96) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:746) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
```

When I type in the command /echopet, I receive this error:

```
[14:32:50 INFO]: -------- EchoPet --------
[14:32:50 INFO]: Author: DSH105
[14:32:50 INFO]: Version: 2.6.0-b28
[14:32:50 INFO]: Website: http://github.com/DSH105/EchoPet/modules/EchoPet
[14:32:50 INFO]: Commands are registered at runtime to provide you with more dynamic control over the command labels.
[14:32:50 INFO]: Command Registration:
[14:32:50 WARN]: Unexpected exception while parsing console command "echopet"
org.bukkit.command.CommandException: Unhandled exception executing command 'echopet' in plugin EchoPet v2.6.0-b28
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-bbf72f3]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
Caused by: java.lang.UnsupportedClassVersionError: com/dsh105/echopet/libs/dsh105/config/Options : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at com.dsh105.echopet.EchoPetPlugin.onCommand(EchoPetPlugin.java:336) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-952179b-bbf72f3]
	... 8 more
>
```

I hope that you may be able to help me. 
=D

**Comment by CaptainBern** [comment]
"Unsupported major minor 51.0" I suggest you to update your Java.

**Comment by TheCellMC** [comment]
I updated java but I still get the same error. :(

**Comment by DSH105** [comment]
Which version of Java are you running? (`java -version`)

**Comment by TheCellMC** [comment]
I have Java Version 8 Update 45.

I downloaded the plugin on bukkit. Is that where I should have downloaded it?

**Comment by DSH105** [comment]
Yes. 

UnsupportedClassVersionError in this case indicates that your server is running a version of Java less than 1.7 (which EchoPet is compiled with). Ensure you're updating Java on the machine your server is running on and not locally.

**Comment by TheCellMC** [comment]
Now, when I type /pet, nothing happens.

/echopet does work

**Comment by DSH105** [comment]
Then there should be another console error.

**Comment by TheCellMC** [comment]
Here, I have a video: https://drive.google.com/file/d/0ByNsn_8PNCpNbUk3dHZucFY3Q0E/view?usp=sharing

**Comment by TheCellMC** [comment]
Do you know how i can fix it?
