### ISSUE TITLE
Missing PetGoalMeleeAttack

### ISSUE THREAD

**Issue by Htgan** [DSH105/EchoPet#524]
Not sure if this was missed out on purpose or by accident

java.lang.ClassNotFoundException: com.dsh105.echopet.compat.nms.v1_8_R2.entity.ai.PetGoalMeleeAttack

:dancers:

**Comment by DSH105** [comment]
Can I see the entire stacktrace? :)

**Comment by Htgan** [comment]
Actually if you look at here https://github.com/DSH105/EchoPet/tree/master/modules/v1_8_R2/src/main/java/com/dsh105/echopet/compat/nms/v1_8_R2/entity/ai
and compare it to the preceding module
https://github.com/DSH105/EchoPet/tree/master/modules/v1_8_R1/src/main/java/com/dsh105/echopet/compat/nms/v1_8_R1/entity/ai
you can see there are some missing.

**Comment by Htgan** [comment]
Basically I was trying to make the pet attack whichever entity the owner attaks.

I'm not sure if this is the right way to do it but I can't test it out since the pet goal MeleeAttack is missing from 1_8_R2

	@EventHandler
	public void onHit(EntityDamageByEntityEvent e) {
		Entity damager = e.getDamager();
		if(damager instanceof Player) {
			Player player = (Player) damager;
			if(!getPetAPI().hasPet(player)) {
				return;
			}
			
			IPet pet = getPetAPI().getPet(player);
			getPetAPI().setAttackTarget(pet, (LivingEntity) e.getEntity());
			getPetAPI().addGoal(pet, GoalType.ATTACK);
		}
	}

**Comment by Htgan** [comment]
I suspect that I haven't done it right, because I don't understand how the pet goal works at all, also I compiled an edited version where I copy/pasted that PetGoalMeleeAttack.java from v1_8_R1 to v1_8_R2 replacing anything that says "v1_8_R1" to "v1_8_R2", I'm kinda dumb and trial and error is the main approach to every problem.

**Comment by Htgan** [comment]
Just in case you insist on full stacktrace:

[01:23:12] [Server thread/INFO]: [PetFights] Enabling PetFights v1.0
[01:23:17] [Server thread/INFO]: Htgan issued server command: /mob spider
[01:23:19] [Server thread/INFO]: Event Triggered
[01:23:20] [Server thread/INFO]: Event Triggered
[01:23:20] [Server thread/INFO]: Damager is Player!
[01:23:20] [Server thread/INFO]: Set Target!
[01:23:20] [Server thread/INFO]: Make pet Attack!
[01:23:20] [Server thread/INFO]: [EchoPet][0;31;1m [WARNING] Could not find class: com.dsh105.echopet.compat.nms.v1_8_R2.entity.ai.PetGoalMeleeAttack!
[01:23:20] [Server thread/WARN]: java.lang.ClassNotFoundException: com.dsh105.echopet.compat.nms.v1_8_R2.entity.ai.PetGoalMeleeAttack
[01:23:20] [Server thread/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[01:23:20] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[01:23:20] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[01:23:20] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at com.dsh105.echopet.compat.api.util.ReflectionUtil.getClass(ReflectionUtil.java:95)
[01:23:20] [Server thread/WARN]: 	at com.dsh105.echopet.compat.api.util.ReflectionUtil.getVersionedClass(ReflectionUtil.java:104)
[01:23:20] [Server thread/WARN]: 	at com.dsh105.echopet.api.EchoPetAPI.addGoal(EchoPetAPI.java:305)
[01:23:20] [Server thread/WARN]: 	at us.riftmc.htgan.petfights.PetFights.onHit(PetFights.java:51)
[01:23:20] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:23:20] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:86)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:539)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452)
[01:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:571)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.EntityMonster.damageEntity(EntityMonster.java:42)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.EntityHuman.attack(EntityHuman.java:1001)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.EntityPlayer.attack(EntityPlayer.java:1060)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1345)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[01:23:20] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[01:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[01:23:20] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[01:23:20] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PetFights v1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:539) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:571) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityMonster.damageEntity(EntityMonster.java:42) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityHuman.attack(EntityHuman.java:1001) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityPlayer.attack(EntityPlayer.java:1060) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1345) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot18.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.<init>(SafeConstructor.java:36) ~[?:?]
	at com.dsh105.echopet.api.EchoPetAPI.addGoal(EchoPetAPI.java:305) ~[?:?]
	at us.riftmc.htgan.petfights.PetFights.onHit(PetFights.java:51) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot18.jar:git-Spigot-870264a-0a645a2]
	... 24 more

**Comment by DSH105** [comment]
Attacking isn't implemented yet, nor has it ever been. I can add the class into the 1_8_R2 module, but it won't make a difference.

**Comment by Htgan** [comment]
;O I was so thrilled, i was looking forward to it.
Would it be possible to make the pet attack an entity with my code? By attack I mean melee attack up close. So making the pet chase down the enemy and attack them until they die.
If it is remotely possible I'll try everything I can. If not I'll have to go with throwing projectile from the pet location.

**Comment by DSH105** [comment]
Not really, sorry :\. Pet skills were being [worked on for EchoPet 3](http://dev.bukkit.org/bukkit-plugins/echopet/forum/72394) back when development was more active, so all I can suggest is waiting for that to be completed.

My apologies that I can't really help you out much here; the v2 infrastructure isn't overly supportive of this kind of feature :(.

**Comment by StevePavlin** [comment]
I began to do some work on this and found all the v1.8.3 NMS methods that were used in the last developed version.

I created a gist of the class here: https://gist.github.com/StevePavlin/26039419f7c4374e2fc9

If you can implement this, that would be extremely helpful.

**Comment by DSH105** [comment]
I didn't think the feature was in a working state before the 1.8.3 update anyway. Had you tested it out before then?

**Comment by StevePavlin** [comment]
No I haven't, it seems like it was still included in the pet AI in version 1.8 R1 all I have done was scan the NMS 1.8.3 classes that were modified in the last working version of this class, and change them to the current working methods/fields. I'm sure that they will work.

What I'm asking for, is if its possible for you to implement this using the API's addGoal() method because the current build is missing this class.

**Comment by DSH105** [comment]
No, I was wondering if it ever did work in previous versions. Even if it's added it may not function correctly as it wasn't really completed.
