### ISSUE TITLE
ProtocolHack

### ISSUE THREAD

**Issue by Townville** [DSH105/EchoPet#532]
Hello,

i'm using Spigot 1649. I now it doesn't support it anymore, but every version which "should" support it doesn't.
Can you pls tell me if this Version is compatible with any version?

**Comment by DSH105** [comment]
From memory, anything from [2.5.0](http://dev.bukkit.org/bukkit-plugins/echopet/files/31-echo-pet-v2-5-0/) up to and not including 2.6.0 should support the protocol 1.8 Spigot. So if you want the most recent, I recommend using [build 25](https://ci.dsh105.com/job/EchoPet-v2/25/) from the CI. Support for the protocol builds was removed in any subsequent versions.

Hopefully that helps :).

**Comment by Townville** [comment]
Now it's working, but everytime a spawn an animal, it says this:
[21:21:50] [Server thread/INFO]: LoganBwDE issued server command: /pet bat
[21:21:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet bat' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for LoganBwDE
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 12 more
Caused by: java.lang.IllegalStateException: Failed to create pet object for LoganBwDE
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 12 more
Caused by: java.lang.RuntimeException: Failed to load class: net.minecraft.server.v1_7_R4.EnumProtocolDirection
    at com.dsh105.echopet.libs.captainbern.reflection.providers.StandardReflectionProvider.loadClass(StandardReflectionProvider.java:24) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.reflection.utils.ClassCache.getClass(ClassCache.java:32) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.reflection.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:291) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketRegistry.registerPackets(PacketRegistry.java:57) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketRegistry.<init>(PacketRegistry.java:31) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketType.getRegistry(PacketType.java:366) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketType.getPacketClass(PacketType.java:398) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.wrapper.WrappedPacket.<init>(WrappedPacket.java:25) ~[?:?]
    at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:64) ~[?:?]
    at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:95) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:57) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:33) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
    at com.dsh105.echopet.api.pet.type.BatPet.<init>(BatPet.java:33) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.EnumProtocolDirection
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
    at com.dsh105.echopet.libs.captainbern.reflection.providers.StandardReflectionProvider.loadClass(StandardReflectionProvider.java:22) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.reflection.utils.ClassCache.getClass(ClassCache.java:32) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.reflection.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:291) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketRegistry.registerPackets(PacketRegistry.java:57) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketRegistry.<init>(PacketRegistry.java:31) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketType.getRegistry(PacketType.java:366) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.protocol.PacketType.getPacketClass(PacketType.java:398) ~[?:?]
    at com.dsh105.echopet.libs.captainbern.wrapper.WrappedPacket.<init>(WrappedPacket.java:25) ~[?:?]
    at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:64) ~[?:?]
    at com.dsh105.echopet.libs.dsh105.particle.ParticleBuilder.show(ParticleBuilder.java:95) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:57) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.SpawnUtil.spawn(SpawnUtil.java:33) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
    at com.dsh105.echopet.api.pet.type.BatPet.<init>(BatPet.java:33) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:143) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:120) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 12 more
[21:21:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NullPointerException
    at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.getLocation(EntityPet.java:135) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.onLive(EntityPet.java:332) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityBatPet.onLive(EntityBatPet.java:61) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:462) ~[?:?]
    at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 4 more
[21:21:50] [Server thread/ERROR]:     Cause of unexpected exception was
java.lang.NullPointerException
    at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.getLocation(EntityPet.java:135) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.onLive(EntityPet.java:332) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityBatPet.onLive(EntityBatPet.java:61) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:462) ~[?:?]
    at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [start.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

Hope you can help me :D
