### ISSUE TITLE
Issue with pet spawning

### ISSUE THREAD

**Issue by Dra5tic** [DSH105/EchoPet#555]
Hi, I am getting this error when players are trying to spawn in pets (using command or pet select). In advance, thanks for the help. (Plugin was working fine until the other day)

EchoPet v2.8.0
Spigot 1.8

[12:25:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EchoPet v2.8.0-b52
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1519) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Bukkit-606cf0e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [minecraft_server.jar:git-Bukkit-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [minecraft_server.jar:git-Bukkit-606cf0e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing 'pet wither' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:244) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:105) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[minecraft_server.jar:git-Bukkit-606cf0e]
... 14 more
Caused by: java.lang.NullPointerException
at com.sk89q.worldguard.bukkit.RegionContainer.get(RegionContainer.java:236) ~[?:?]
at com.sk89q.worldguard.protection.GlobalRegionManager.get(GlobalRegionManager.java:78) ~[?:?]
at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:1026) ~[?:?]
at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:41) ~[?:?]
at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:32) ~[?:?]
at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:109) ~[?:?]
at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:412) ~[?:?]
at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:244) ~[minecraft_server.jar:git-Bukkit-606cf0e]
at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:105) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[minecraft_server.jar:git-Bukkit-606cf0e]
... 14 more

**Comment by DSH105** [comment]
What version of WorldGuard are you running?

**Comment by Dra5tic** [comment]
worldguard-6.0.0-SNAPSHOT is the file name if that helps? Sorry, I'm very new to this sort of stuff.
