### ISSUE TITLE
Using any command and using v2.8

### ISSUE THREAD

**Issue by HurttleTurtle** [DSH105/EchoPet#557]
04:29:22  [Info] [EchoPet] Enabling EchoPet v2.8.1-SNAPSHOT-b67
04:29:27  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:27  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:27  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:27  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:27  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:27  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:27  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:27  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:27  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:27  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:27  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:27  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:27  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:27  [Error] [EchoPet] Unhandled exception occured in onPacketSending(PacketEvent) for EchoPetjava.lang.NullPointerException	at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:143) ~[EchoPet%20(1).jar:?]	at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.isPlayerRunningv1_8(SpigotProtocolHackPacketListener.java:196) ~[EchoPet%20(1).jar:?]	at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.onPacketSending(SpigotProtocolHackPacketListener.java:87) ~[EchoPet%20(1).jar:?]	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib-3.4.0.jar:?]	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib-3.4.0.jar:?]	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188) [ej.class:?]	at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158) [ej.class:?]	at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992) [nh.class:?]	at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375) [my.class:?]	at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381) [my.class:?]	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344) [my.class:?]	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256) [my.class:?]	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276) [mn.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978) [MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
04:29:27  [Error] Parameters: net.minecraft.network.play.server.S1CPacketEntityMetadata@4f969c52 field_149379_a=305 field_149378_b=[net.minecraft.entity.DataWatcher$WatchableObject@185257dd, net.minecraft.entity.DataWatcher$WatchableObject@31e61cf0, net.minecraft.entity.DataWatcher$WatchableObject@235b6ac0, net.minecraft.entity.DataWatcher$WatchableObject@5782ad2a, net.minecraft.entity.DataWatcher$WatchableObject@5d64e4b8, net.minecraft.entity.DataWatcher$WatchableObject@5ce46278, net.minecraft.entity.DataWatcher$WatchableObject@24110e4e, net.minecraft.entity.DataWatcher$WatchableObject@66380c1b, net.minecraft.entity.DataWatcher$WatchableObject@1c836540] timestamp=1440329367733
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:43  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:43  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:43  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:43  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:43  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:43  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:43  [Info] [EchoPet] [WARNING] No such field: playerConnection!
04:29:43  [Warn] java.lang.NoSuchFieldException: playerConnection
04:29:43  [Warn] at java.lang.Class.getDeclaredField(Class.java:2057)
04:29:43  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:127)
04:29:43  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:143)
04:29:43  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.isPlayerRunningv1_8(SpigotProtocolHackPacketListener.java:196)
04:29:43  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.onPacketSending(SpigotProtocolHackPacketListener.java:87)
04:29:43  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
04:29:43  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
04:29:43  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638)
04:29:43  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:43  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:43  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:43  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:43  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:43  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:43  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:43  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:43  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:43  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:47  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:47  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:47  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:47  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:47  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:47  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:47  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:47  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:47  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:47  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:47  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:47  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:47  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:47  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:47  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:47  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:47  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:47  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:48  [Info] [EchoPet] [WARNING] No such field: playerConnection!
04:29:48  [Warn] java.lang.NoSuchFieldException: playerConnection
04:29:48  [Warn] at java.lang.Class.getDeclaredField(Class.java:2057)
04:29:48  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:127)
04:29:48  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:143)
04:29:48  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.isPlayerRunningv1_8(SpigotProtocolHackPacketListener.java:196)
04:29:48  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.onPacketSending(SpigotProtocolHackPacketListener.java:87)
04:29:48  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
04:29:48  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
04:29:48  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638)
04:29:48  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:48  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:48  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:48  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:48  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:48  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:48  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:48  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:48  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:48  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:48  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:48  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:48  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:48  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:48  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:54  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:54  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:54  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:54  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:54  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:54  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:54  [Info] [EchoPet] [WARNING] No such field: playerConnection!
04:29:54  [Warn] java.lang.NoSuchFieldException: playerConnection
04:29:54  [Warn] at java.lang.Class.getDeclaredField(Class.java:2057)
04:29:54  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:127)
04:29:54  [Warn] at com.dsh105.echopet.compat.api.util.ReflectionUtil.getField(ReflectionUtil.java:143)
04:29:54  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.isPlayerRunningv1_8(SpigotProtocolHackPacketListener.java:196)
04:29:54  [Warn] at com.dsh105.echopet.compatibility.SpigotProtocolHackPacketListener.onPacketSending(SpigotProtocolHackPacketListener.java:87)
04:29:54  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
04:29:54  [Warn] at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
04:29:54  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638)
04:29:54  [Warn] at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
04:29:54  [Warn] at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
04:29:54  [Warn] at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:188)
04:29:54  [Warn] at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:158)
04:29:54  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:992)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:375)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:381)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:344)
04:29:54  [Warn] at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:256)
04:29:54  [Warn] at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:276)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
04:29:54  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:29:54  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:29:54  [Warn] at java.lang.Thread.run(Thread.java:745)
04:29:59  [Warn] at com.dsh105.echopet.libs.com.dsh105.commodus.reflection.Reflection.getClass(Reflection.java:64)
04:29:59  [Warn] at com.dsh105.echopet.libs.com.dsh105.commodus.reflection.Reflection.getNMSClass(Reflection.java:83)
04:29:59  [Warn] at com.dsh105.echopet.libs.com.dsh105.powermessage.core.PowerMessage.<clinit>(PowerMessage.java:67)
04:29:59  [Warn] at com.dsh105.echopet.commands.HelpEntry.getPowerMessage(HelpEntry.java:95)
04:29:59  [Warn] at com.dsh105.echopet.commands.PetCommand.getHelp(PetCommand.java:55)
04:29:59  [Warn] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:289)
04:29:59  [Warn] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46)
04:30:00  [Warn] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
04:30:00  [Warn] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
04:30:00  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
04:30:00  [Warn] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
04:30:00  [Warn] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
04:30:00  [Warn] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
04:30:00  [Warn] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
04:30:00  [Warn] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
04:30:00  [Warn] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
04:30:00  [Warn] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
04:30:00  [Warn] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
04:30:00  [Warn] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
04:30:00  [Warn] at java.lang.Thread.run(Thread.java:745)
04:30:00  [Error] org.bukkit.command.CommandException: Unhandled exception executing 'pet help' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1448.121]	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1448.121]	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]Caused by: java.lang.ExceptionInInitializerError	at com.dsh105.echopet.commands.HelpEntry.getPowerMessage(HelpEntry.java:95) ~[?:?]	at com.dsh105.echopet.commands.PetCommand.getHelp(PetCommand.java:55) ~[?:?]	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:289) ~[?:?]	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1448.121]	... 12 moreCaused by: java.lang.NullPointerException	at com.dsh105.echopet.libs.com.dsh105.powermessage.core.PowerMessage.<clinit>(PowerMessage.java:71) ~[?:?]	at com.dsh105.echopet.commands.HelpEntry.getPowerMessage(HelpEntry.java:95) ~[?:?]	at com.dsh105.echopet.commands.PetCommand.getHelp(PetCommand.java:55) ~[?:?]	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:289) ~[?:?]	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1448.121]	... 12 more

**Comment by HurttleTurtle** [comment]
I can't do any /pet or /pet help commands. And when I use the v2.8 on the Bukkit site. It tells me that it's out of date...
