### ISSUE TITLE
1.8.8 Spigot Support

### ISSUE THREAD

**Issue by drew5494** [DSH105/EchoPet#582]
Hey, Will the plugin be made compatible with this?

**Comment by i9hdkill** [comment]
It's compatible since months.
You can get it here
https://ci.dsh105.com/job/EchoPet-v2/changes

**Comment by drew5494** [comment]
Well I still get this error whenever I use it
[17:32:22 WARN]: [EchoPet] Task #213 for EchoPet v2.8.1-SNAPSHOT-b69 generated an exception
com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for Tassoon
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPetFromFile(PetManager.java:238) ~[?:?]
	at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:74) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$1.run(PetOwnerListener.java:179) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalStateException: Failed to create pet object for Tassoon
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
Caused by: java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:107) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:128) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:793) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at com.dsh105.echopet.libs.com.captainbern.minecraft.reflection.MinecraftMethods.sendPacket(MinecraftMethods.java:46) ~[?:?]
	at com.dsh105.echopet.libs.com.dsh105.commodus.ServerUtil.sendPacket(ServerUtil.java:206) ~[?:?]
	at com.dsh105.echopet.libs.com.dsh105.commodus.particle.ParticleBuilder.show(ParticleBuilder.java:78) ~[?:?]
	at com.dsh105.echopet.libs.com.dsh105.commodus.particle.ParticleBuilder.show(ParticleBuilder.java:95) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.SpawnUtil.spawn(SpawnUtil.java:57) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.SpawnUtil.spawn(SpawnUtil.java:33) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:60) ~[?:?]
	at com.dsh105.echopet.api.pet.type.SnowmanPet.<init>(SnowmanPet.java:30) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	... 13 more
[17:32:24 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Ticking entity
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.getLocation(EntityPet.java:133) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.ai.PetGoalFollowOwner.tick(PetGoalFollowOwner.java:128) ~[?:?]
	at com.dsh105.echopet.compat.api.ai.PetGoalSelector.updateGoals(PetGoalSelector.java:175) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.t_(EntityPet.java:459) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	... 4 more
[17:32:24 ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.getLocation(EntityPet.java:133) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.ai.PetGoalFollowOwner.tick(PetGoalFollowOwner.java:128) ~[?:?]
	at com.dsh105.echopet.compat.api.ai.PetGoalSelector.updateGoals(PetGoalSelector.java:175) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.t_(EntityPet.java:459) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:32:24 ERROR]: This crash report has been saved to: /Users/Drew/Documents/_/./crash-reports/crash-2015-11-27_17.32.24-server.txt

**Comment by i9hdkill** [comment]
Can you list your plugins?
Any other plugins that are manipulating entities?

**Comment by drew5494** [comment]
Not sure but #559 and others seem to be having the same problems.

**Comment by drew5494** [comment]
It seems if you create a new world it works fine...
