### ISSUE TITLE
NullPointerException at ownerRidePet(Pet.java.353) when teleporting player via Command Block

### ISSUE THREAD

**Issue by brandonbisel** [DSH105/EchoPet#615]
The following NullPointerException and server crash happens when a player activates a Command Block containing `/tp @p 0 100 0 180 0` while riding a pet in Spigot 1.10.2, EchoPet 1.0.3-b40:

```
[21:31:45] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking entity
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:810) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at com.dsh105.echopet.api.pet.Pet.ownerRidePet(Pet.java:353) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityPet.onLive(EntityPet.java:287) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityPet.m(EntityPet.java:462) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityAgeablePet.m(EntityAgeablePet.java:79) ~[?:?]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1604) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        ... 4 more
[21:31:45] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at com.dsh105.echopet.api.pet.Pet.ownerRidePet(Pet.java:353) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityPet.onLive(EntityPet.java:287) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityPet.m(EntityPet.java:462) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_10_R1.entity.EntityAgeablePet.m(EntityAgeablePet.java:79) ~[?:?]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1604) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[21:31:45] [Server thread/ERROR]: This crash report has been saved to: /home/spigot/./crash-reports/crash-2016-08-26_21.31.45-server.txt
```

```
Version: 1.10.2
Software: CraftBukkit on Bukkit 1.10.2-R0.1-SNAPSHOT
Plugins:
EchoPet 1.0.3-b40
Vault 1.5.6-b49
ProtectionLib 0.5.4
LightAPI 3.2.1
ProtocolLib 4.1.0-SNAPSHOT-b311
FurnitureLib 1.7.4
FurnitureMaker 1.2
DiceFurniture 2.9.3
```

**Comment by brandonbisel** [comment]
Sorry, just realized this is the wrong Issue Tracker page. Reposted on Borlea/EchoPet fork.
